### ISSUE TITLE
Fix Event Prizes Cards

### ISSUE THREAD

**Issue by haxzie-xx** [meenhacks/meenhacks.github.io#11]
Event prizes are something that needs to be highlighted, avoid using hover effects on it and present it with its own layout separate from registration.

PS. It'd be great if you change the button colors (Yellowish) to something more attractive.

**Comment by athul** [comment]
We should make the issues look more coloful I think(like the CE issues)

**Comment by athul** [comment]
I think the reference PR resolves this.

**Comment by athul** [comment]
Thus Im closing it
